// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.0
// source: gateway/middleware/auth/v1/auth.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// logging middleware config.
type Casbin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model  []string `protobuf:"bytes,1,rep,name=model,proto3" json:"model,omitempty"`
	Policy []string `protobuf:"bytes,2,rep,name=policy,proto3" json:"policy,omitempty"`
}

func (x *Casbin) Reset() {
	*x = Casbin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_middleware_auth_v1_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Casbin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Casbin) ProtoMessage() {}

func (x *Casbin) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_middleware_auth_v1_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Casbin.ProtoReflect.Descriptor instead.
func (*Casbin) Descriptor() ([]byte, []int) {
	return file_gateway_middleware_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *Casbin) GetModel() []string {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *Casbin) GetPolicy() []string {
	if x != nil {
		return x.Policy
	}
	return nil
}

type Auth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key             string           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	JwtCheckRouters map[string]int64 `protobuf:"bytes,2,rep,name=jwt_check_routers,json=jwtCheckRouters,proto3" json:"jwt_check_routers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Casbin          *Casbin          `protobuf:"bytes,3,opt,name=casbin,proto3" json:"casbin,omitempty"`
}

func (x *Auth) Reset() {
	*x = Auth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_middleware_auth_v1_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_middleware_auth_v1_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_gateway_middleware_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *Auth) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Auth) GetJwtCheckRouters() map[string]int64 {
	if x != nil {
		return x.JwtCheckRouters
	}
	return nil
}

func (x *Auth) GetCasbin() *Casbin {
	if x != nil {
		return x.Casbin
	}
	return nil
}

var File_gateway_middleware_auth_v1_auth_proto protoreflect.FileDescriptor

var file_gateway_middleware_auth_v1_auth_proto_rawDesc = []byte{
	0x0a, 0x25, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65,
	0x77, 0x61, 0x72, 0x65, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x75, 0x74,
	0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x2e, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x61, 0x75, 0x74, 0x68,
	0x2e, 0x76, 0x31, 0x22, 0x36, 0x0a, 0x06, 0x43, 0x61, 0x73, 0x62, 0x69, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x22, 0xfb, 0x01, 0x0a, 0x04,
	0x41, 0x75, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x61, 0x0a, 0x11, 0x6a, 0x77, 0x74, 0x5f, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x35, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x6d, 0x69, 0x64, 0x64,
	0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x41,
	0x75, 0x74, 0x68, 0x2e, 0x4a, 0x77, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0f, 0x6a, 0x77, 0x74, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x73, 0x12, 0x3a, 0x0a, 0x06, 0x63, 0x61, 0x73,
	0x62, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2e, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x61,
	0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x73, 0x62, 0x69, 0x6e, 0x52, 0x06, 0x63,
	0x61, 0x73, 0x62, 0x69, 0x6e, 0x1a, 0x42, 0x0a, 0x14, 0x4a, 0x77, 0x74, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x6b, 0x72, 0x61, 0x74, 0x6f,
	0x73, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x77, 0x61, 0x72, 0x65,
	0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gateway_middleware_auth_v1_auth_proto_rawDescOnce sync.Once
	file_gateway_middleware_auth_v1_auth_proto_rawDescData = file_gateway_middleware_auth_v1_auth_proto_rawDesc
)

func file_gateway_middleware_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_gateway_middleware_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_gateway_middleware_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_gateway_middleware_auth_v1_auth_proto_rawDescData)
	})
	return file_gateway_middleware_auth_v1_auth_proto_rawDescData
}

var file_gateway_middleware_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gateway_middleware_auth_v1_auth_proto_goTypes = []interface{}{
	(*Casbin)(nil), // 0: gateway.middleware.auth.v1.Casbin
	(*Auth)(nil),   // 1: gateway.middleware.auth.v1.Auth
	nil,            // 2: gateway.middleware.auth.v1.Auth.JwtCheckRoutersEntry
}
var file_gateway_middleware_auth_v1_auth_proto_depIdxs = []int32{
	2, // 0: gateway.middleware.auth.v1.Auth.jwt_check_routers:type_name -> gateway.middleware.auth.v1.Auth.JwtCheckRoutersEntry
	0, // 1: gateway.middleware.auth.v1.Auth.casbin:type_name -> gateway.middleware.auth.v1.Casbin
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gateway_middleware_auth_v1_auth_proto_init() }
func file_gateway_middleware_auth_v1_auth_proto_init() {
	if File_gateway_middleware_auth_v1_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gateway_middleware_auth_v1_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Casbin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_middleware_auth_v1_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Auth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gateway_middleware_auth_v1_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_middleware_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_gateway_middleware_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_gateway_middleware_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_gateway_middleware_auth_v1_auth_proto = out.File
	file_gateway_middleware_auth_v1_auth_proto_rawDesc = nil
	file_gateway_middleware_auth_v1_auth_proto_goTypes = nil
	file_gateway_middleware_auth_v1_auth_proto_depIdxs = nil
}
